"""trashmy.tech — 35 AI user personas for website stress-testing."""

import random

PERSONAS = [
    # ── ACCESSIBILITY (5) ──────────────────────────────────────
    {
        "id": "A1", "name": "Margaret Liu", "age": 68,
        "category": "accessibility",
        "description": "Retired teacher with low vision who zooms everything to 200%",
        "avatar_emoji": "👵", "task_style": "slow_careful",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 2000, "misclick_rate": 0.15,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "A2", "name": "James Whitfield", "age": 74,
        "category": "accessibility",
        "description": "Veteran who navigates entirely with keyboard — no mouse",
        "avatar_emoji": "⌨️", "task_style": "keyboard_nav",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 800, "misclick_rate": 0.0,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": True, "input_strategy": "normal",
            "patience_threshold_ms": 45000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "A3", "name": "Priya Sharma", "age": 31,
        "category": "accessibility",
        "description": "Blind software engineer who relies on screen reader and ARIA labels",
        "avatar_emoji": "🧑‍🦯", "task_style": "screen_reader",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 600, "misclick_rate": 0.0,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": True, "input_strategy": "normal",
            "patience_threshold_ms": 30000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "A4", "name": "Carlos Mendes", "age": 45,
        "category": "accessibility",
        "description": "Colorblind designer (deuteranopia) who can't distinguish red/green",
        "avatar_emoji": "🎨", "task_style": "visual_check",
        "viewport": {"width": 1440, "height": 900},
        "behavioral_modifiers": {
            "click_delay_ms": 400, "misclick_rate": 0.05,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 30000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "A5", "name": "Lin Zhang", "age": 52,
        "category": "accessibility",
        "description": "Motor-impaired user with shaky hands and high misclick rate",
        "avatar_emoji": "🤲", "task_style": "careful_clicks",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 1500, "misclick_rate": 0.25,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 45000, "double_clicks": True,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },

    # ── DEMOGRAPHIC (5) ────────────────────────────────────────
    {
        "id": "D1", "name": "Jayden Reeves", "age": 13,
        "category": "demographic",
        "description": "Teenager who clicks lightning-fast and never reads anything",
        "avatar_emoji": "👦", "task_style": "speed_scan",
        "viewport": {"width": 390, "height": 844},
        "behavioral_modifiers": {
            "click_delay_ms": 100, "misclick_rate": 0.08,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "minimal",
            "patience_threshold_ms": 8000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "D2", "name": "Fatima Al-Rashid", "age": 35,
        "category": "demographic",
        "description": "Non-native English speaker confused by idioms and jargon",
        "avatar_emoji": "🌐", "task_style": "confused_reader",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 900, "misclick_rate": 0.10,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 40000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "D3", "name": "Aiko Tanaka", "age": 22,
        "category": "demographic",
        "description": "Mobile-first user in Tokyo on a small phone screen",
        "avatar_emoji": "📱", "task_style": "mobile_thumb",
        "viewport": {"width": 375, "height": 812},
        "behavioral_modifiers": {
            "click_delay_ms": 200, "misclick_rate": 0.12,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 15000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "D4", "name": "Pat Donovan", "age": 35,
        "category": "demographic",
        "description": "Parent holding a baby in one hand, tapping with the other",
        "avatar_emoji": "👶", "task_style": "one_handed",
        "viewport": {"width": 390, "height": 844},
        "behavioral_modifiers": {
            "click_delay_ms": 700, "misclick_rate": 0.20,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "minimal",
            "patience_threshold_ms": 12000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "D5", "name": "Sam Brennan", "age": 65,
        "category": "demographic",
        "description": "Retiree on a tablet who taps slowly and reads every word",
        "avatar_emoji": "📖", "task_style": "slow_reader",
        "viewport": {"width": 1024, "height": 1366},
        "behavioral_modifiers": {
            "click_delay_ms": 1200, "misclick_rate": 0.08,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },

    # ── CHAOS (5) ──────────────────────────────────────────────
    {
        "id": "C1", "name": "Ben Torres", "age": 28,
        "category": "chaos",
        "description": "Mashes the back button after every other action",
        "avatar_emoji": "⬅️", "task_style": "chaotic",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 300, "misclick_rate": 0.05,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 20000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "C2", "name": "Kai Nakamura", "age": 24,
        "category": "chaos",
        "description": "Puts SQL injection, emojis, and garbage into every form field",
        "avatar_emoji": "💣", "task_style": "adversarial",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 200, "misclick_rate": 0.0,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "adversarial",
            "patience_threshold_ms": 30000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "C3", "name": "Zara Phillips", "age": 19,
        "category": "chaos",
        "description": "Tries to complete every flow as fast as humanly possible",
        "avatar_emoji": "⚡", "task_style": "speed_run",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 50, "misclick_rate": 0.10,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "minimal",
            "patience_threshold_ms": 5000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "C4", "name": "Dan Okafor", "age": 44,
        "category": "chaos",
        "description": "Double-clicks absolutely everything including links and buttons",
        "avatar_emoji": "🖱️", "task_style": "double_click",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 300, "misclick_rate": 0.05,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 20000, "double_clicks": True,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "C5", "name": "Riley Chen", "age": 21,
        "category": "chaos",
        "description": "Gives up after 3 seconds of waiting for anything",
        "avatar_emoji": "😤", "task_style": "impatient",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 150, "misclick_rate": 0.05,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 3000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": True,
        },
    },

    # ── BEHAVIORAL (5) ─────────────────────────────────────────
    {
        "id": "B1", "name": "Monica Reeves", "age": 40,
        "category": "behavioral",
        "description": "Checks the privacy policy and terms before doing anything",
        "avatar_emoji": "🔍", "task_style": "cautious",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 600, "misclick_rate": 0.02,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 45000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "B2", "name": "Noah Andersen", "age": 28,
        "category": "behavioral",
        "description": "Clicks every link and visits every page before taking action",
        "avatar_emoji": "🧭", "task_style": "explorer",
        "viewport": {"width": 1440, "height": 900},
        "behavioral_modifiers": {
            "click_delay_ms": 500, "misclick_rate": 0.03,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "B3", "name": "Suki Patel", "age": 33,
        "category": "behavioral",
        "description": "Does the absolute minimum — skips every optional field",
        "avatar_emoji": "✂️", "task_style": "minimal",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 300, "misclick_rate": 0.02,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "minimal",
            "patience_threshold_ms": 20000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "B4", "name": "Diane Kowalski", "age": 55,
        "category": "behavioral",
        "description": "Trying to sign up on behalf of their kid, confused by everything",
        "avatar_emoji": "😵", "task_style": "confused",
        "viewport": {"width": 1024, "height": 768},
        "behavioral_modifiers": {
            "click_delay_ms": 1200, "misclick_rate": 0.15,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 30000, "double_clicks": True,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "B5", "name": "Alex Mercer", "age": 25,
        "category": "behavioral",
        "description": "Uses keyboard shortcuts, Ctrl+F, and expects everything to be fast",
        "avatar_emoji": "💻", "task_style": "power_user",
        "viewport": {"width": 1920, "height": 1080},
        "behavioral_modifiers": {
            "click_delay_ms": 150, "misclick_rate": 0.01,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 5000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },

    # ── PORTFOLIO / HARDCORE (10) ──────────────────────────────
    {
        "id": "P1", "name": "David Park", "age": 42,
        "category": "portfolio",
        "description": "VP of Engineering reviewing your portfolio to decide on an interview. Clicks projects, checks links, judges load time.",
        "avatar_emoji": "👔", "task_style": "evaluator",
        "viewport": {"width": 1440, "height": 900},
        "behavioral_modifiers": {
            "click_delay_ms": 400, "misclick_rate": 0.02,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 10000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "P2", "name": "Sarah Mitchell", "age": 29,
        "category": "portfolio",
        "description": "Tech recruiter who has 30 seconds per portfolio. Scans for contact info, GitHub link, and resume download.",
        "avatar_emoji": "📋", "task_style": "speed_scan",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 150, "misclick_rate": 0.05,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 8000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "P3", "name": "Tomas Herrera", "age": 34,
        "category": "portfolio",
        "description": "Recruiter reviewing portfolios on their phone during commute. Tests responsive design, touch targets, scrolling.",
        "avatar_emoji": "🚇", "task_style": "mobile_thumb",
        "viewport": {"width": 375, "height": 812},
        "behavioral_modifiers": {
            "click_delay_ms": 300, "misclick_rate": 0.15,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 12000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "P4", "name": "Leah Fontaine", "age": 31,
        "category": "portfolio",
        "description": "Senior UI designer who judges visual hierarchy, spacing, typography, and color contrast harshly.",
        "avatar_emoji": "🎨", "task_style": "visual_check",
        "viewport": {"width": 1920, "height": 1080},
        "behavioral_modifiers": {
            "click_delay_ms": 800, "misclick_rate": 0.01,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 45000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "P5", "name": "Marcus Webb", "age": 30,
        "category": "portfolio",
        "description": "QA engineer who clicks every single link and button to find 404s, broken anchors, and dead ends.",
        "avatar_emoji": "🔗", "task_style": "explorer",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 100, "misclick_rate": 0.0,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "P6", "name": "Ruth Kamau", "age": 38,
        "category": "portfolio",
        "description": "User on a slow 3G connection in rural area. Everything takes forever. Tests if the site is usable with slow loading.",
        "avatar_emoji": "🐌", "task_style": "slow_careful",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 2000, "misclick_rate": 0.05,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": True,
        },
    },
    {
        "id": "P7", "name": "Ethan Byrne", "age": 26,
        "category": "portfolio",
        "description": "Opens every project in a new tab, right-clicks everything, tests if links open correctly.",
        "avatar_emoji": "📑", "task_style": "explorer",
        "viewport": {"width": 1440, "height": 900},
        "behavioral_modifiers": {
            "click_delay_ms": 200, "misclick_rate": 0.03,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 30000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "P8", "name": "Yuki Endo", "age": 26,
        "category": "portfolio",
        "description": "Specifically targets contact forms and submission flows. Tries empty submissions, invalid emails, XSS payloads.",
        "avatar_emoji": "📧", "task_style": "adversarial",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 200, "misclick_rate": 0.0,
            "reads_everything": False, "skips_text": True,
            "keyboard_only": False, "input_strategy": "adversarial",
            "patience_threshold_ms": 30000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "P9", "name": "Angela Rivera", "age": 45,
        "category": "portfolio",
        "description": "Accessibility expert who tabs through the entire page, checks focus order, ARIA labels, and heading hierarchy.",
        "avatar_emoji": "♿", "task_style": "screen_reader",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 400, "misclick_rate": 0.0,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": True, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "P10", "name": "Jake Lindqvist", "age": 27,
        "category": "portfolio",
        "description": "Developer on an ultrawide 4K monitor. Tests if the layout stretches or breaks at extreme widths.",
        "avatar_emoji": "🖥️", "task_style": "power_user",
        "viewport": {"width": 2560, "height": 1440},
        "behavioral_modifiers": {
            "click_delay_ms": 150, "misclick_rate": 0.01,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 15000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },

    # ── CONTENT / SEO (5) ──────────────────────────────────────
    {
        "id": "S1", "name": "Dr. Sarah Mitchell", "age": 42,
        "category": "content_seo",
        "description": "Content evaluator who reads ALL visible text, scores readability (Flesch-Kincaid), checks heading hierarchy, validates meta tags, structured data, and image alt text coverage.",
        "avatar_emoji": "📝", "task_style": "content_evaluator",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 600, "misclick_rate": 0.01,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "S2", "name": "Alex Rivera", "age": 29,
        "category": "content_seo",
        "description": "Value proposition tester who evaluates above-the-fold content in 5 seconds: headline clarity, CTA specificity, and whether the site communicates what it does instantly.",
        "avatar_emoji": "🎯", "task_style": "value_prop_tester",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 200, "misclick_rate": 0.02,
            "reads_everything": False, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 15000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "S3", "name": "Rachel Torres", "age": 36,
        "category": "content_seo",
        "description": "Skeptic reader who hunts for trust signals: privacy policy, terms, contact info, about page, social proof, and credibility indicators. Flags red flags like broken links and missing HTTPS.",
        "avatar_emoji": "🔐", "task_style": "skeptic_reader",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 500, "misclick_rate": 0.02,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 45000, "double_clicks": False,
            "uses_back_button": True, "refreshes_randomly": False,
        },
    },
    {
        "id": "S4", "name": "Googlebot", "age": None,
        "category": "content_seo",
        "description": "Search engine crawler that checks robots.txt, sitemap.xml, canonical URLs, JavaScript rendering dependency, mobile-friendliness, Core Web Vitals indicators, and structured data validity.",
        "avatar_emoji": "🤖", "task_style": "googlebot_simulator",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 100, "misclick_rate": 0.0,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 60000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
    {
        "id": "S5", "name": "Social Bot", "age": None,
        "category": "content_seo",
        "description": "Social media link preview bot that validates Open Graph tags, Twitter Card tags, share image resolution, and composes a share preview quality rating.",
        "avatar_emoji": "📣", "task_style": "social_bot_simulator",
        "viewport": {"width": 1280, "height": 720},
        "behavioral_modifiers": {
            "click_delay_ms": 100, "misclick_rate": 0.0,
            "reads_everything": True, "skips_text": False,
            "keyboard_only": False, "input_strategy": "normal",
            "patience_threshold_ms": 30000, "double_clicks": False,
            "uses_back_button": False, "refreshes_randomly": False,
        },
    },
]

ADVERSARIAL_INPUTS = [
    "Robert'); DROP TABLE users;--",
    "🍕🍕🍕🔥💀",
    "<script>alert('xss')</script>",
    "",
    "not-an-email",
    "0000000000",
    "A" * 500,
    "-1",
    "null",
    "undefined",
    "' OR '1'='1",
    "<img src=x onerror=alert(1)>",
    "test@test.com\nBcc: spam@evil.com",
    "../../etc/passwd",
    "99999999999999999999",
    "<svg onload=alert(1)>",
    "javascript:alert(1)",
    "{{7*7}}",
    "${7*7}",
    "admin@admin.com",
    " ",
    "\t\n",
    "test'test",
    'test"test',
    "SELECT * FROM users",
    "<h1>injected</h1>",
    "file:///etc/passwd",
    "%00",
    "a]@a.com",
    "test@",
    "@test.com",
]


def sample_personas(n: int = 20) -> list[dict]:
    """Pick n personas ensuring at least 2 per category. Default 20 for thorough testing."""
    categories = ["accessibility", "demographic", "chaos", "behavioral", "portfolio", "content_seo"]
    selected = []

    for cat in categories:
        pool = [p for p in PERSONAS if p["category"] == cat]
        if pool:
            count = min(2, len(pool))
            selected.extend(random.sample(pool, count))

    remaining = [p for p in PERSONAS if p not in selected]
    extra = min(n - len(selected), len(remaining))
    if extra > 0:
        selected.extend(random.sample(remaining, extra))

    random.shuffle(selected)
    return selected[:n]
